---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-env
data:
  OLC_SUFFIX: dc=k3s,dc=lab
  OLC_ROOTDN: cn=admin,${OLC_SUFFIX}
  OLC_ACCESS: '{0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external, cn=auth" read by dn.base="${OLC_ROOTDN}" read by * none'
...
# vim: set filetype=yaml
