---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-database-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
...
# vim: set filetype=yaml
