---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.megabytes }}Mi
...
# vim: set filetype=yaml
