---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-meta-pv
spec:
  storageClassName: longhorn
  capacity:
    storage: {{ $.Values.meta_storage_mb }}Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: ldap-meta-pvc
      namespace: openldap-system
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-data-pv
spec:
  storageClassName: longhorn
  capacity:
    storage: {{ $.Values.data_storage_mb }}Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: ldap-data-pvc
      namespace: openldap-system
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/longhorn
...
# vim: set filetype=yaml
