---
# this is the headless service used by the statefulset
apiVersion: v1
kind: Service
metadata:
  name: openldap-service
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: 'SingleStack'
  ports: {{ $.Values.ports }}
  publishNotReadyAddresses: false
  selector:
    app: openldap
  type: ClusterIP
  clusterIP: None

# these are extra services to expose the headless service
{{ range .Values.replicas }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: {{ . }}
  ports: {{ $.Values.ports }}
  publishNotReadyAddresses: false
{{ end }}
...
# vim: set filetype=yaml
