---
apiVersion: v1
kind: Service
metadata:
  name: openldap-service
spec:
  ports:
  - name: ldap
    port: {{ .Values.ldap.ldap_port }}
    protocol: TCP
    targetPort: 10389
  - name: ldaps
    port: {{ .Values.ldap.ldaps_port }}
    protocol: TCP
    targetPort: 10636
  # can either use a LoadBalancer or an ingress
  # does ingress support non-HTTP traffic?
  type: ClusterIP
...
# vim: set filetype=yaml
