---
{{- $image := "ghcr.io/dreamtrack-net/tinyldap:2024-10-09" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldap-ss
spec:
  serviceName: ldap-svc-ss
  restartPolicy: Always
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: ldap
  volumeClaimTemplates:
  - metadata:
      name: vc-ldap-meta
    spec:
      storageClassName: longhorn
      accessModes:
      - 'ReadWriteOnce'
      resources:
        requests:
          storage: {{ .Values.meta_storage_mb }}Mi
  - metadata:
      name: vc-ldap-data
    spec:
      storageClassName: longhorn
      accessModes:
      - 'ReadWriteOnce'
      resources:
        requests:
          storage: {{ .Values.data_storage_mb }}Mi
  template:
    metadata:
      labels:
        app: ldap
    spec:
      volumes:
      # certificates.yaml
      - name: vol-ldap-tls
        secret:
          secretName: ldap-tls
      # configMaps.yaml
      - name: vol-ldap-conf
        configMap:
          name: cm-ldap-conf
          items:
          - key: ldap.conf
            path: ldap.conf
      # Thanks to https://vincentdeborger.be/blog/using-initcontainers-to-create-dependencies-on-pods
      # for this trick
      # initContainer: wait for initDone=true
      #initContainers:
      #  - name: wait-for-init-flag
      #    image: kubectl
      #    command:
      #      - /bin/sh
      #      - -c
      #      - |
      #        until kubectl -n openldap-system wait --for=condition=Ready pods -l app=openldap --timeout=300s; do
      #          sleep 5;
      #          echo 'Waiting for slapd...';
      #        done
      containers:
      - name: openldap
        image: {{ $image }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: ldap
          containerPort: 10389
        - name: ldaps
          containerPort: 10636
        volumeMounts:
        - name: vol-ldap-conf
          mountPath: /etc/ldap
        - name: vc-ldap-meta
          mountPath: /etc/ldap/slapd.d
        - name: vc-ldap-data
          mountPath: /var/lib/ldap
        - name: vol-ldap-tls
          mountPath: /etc/tls
          readOnly: true
        readinessProbe:
          exec:
            command:
            - 'bash'
            - '-ec'
            - 'ldapsearch -Y EXTERNAL -H ldapi:/// -b cn=config olcDatabase=\*'
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
...
# vim: set filetype=yaml
