---
image: ghcr.io/dreamtrack-net/tinyldap:2024-10-07

# necessary because the Helm template engine sucks
replicas:
  - openldap-0
  - openldap-1

cert:
  dnsNames:
    - "ldap.k3s.lab"
  # detect issuer? not possible, so this must be scripted
  # can we patch in the issuer later?
  clusterIssuerName: 'k3s-amethyst-issuer'

ldap:
  suffix: 'dc=k3s,dc=lab'
  organisation: 'K3S Amethyst'
  description: 'K3S Amethyst'
  rootRdn: 'admin'
  # dev user passwd
  rootPwHash: "{SSHA}gSIuDVYLAQmbamahlILBugabdWE7Q5ld"
  uris: ldap://ldap.k3s.lab/ ldaps://ldap.k3s.lab/
# wedge: topmost "dc" for organisation. How to get this?
  wedge: k3s
# wedge2: users group name
  wedge2: users

admin:
  username: zeus
  userPwHash: "{SSHA}JWA/xti9Me/iEt8hKqFBV6JcO6BWTKlV"
  homeDir: /mnt/olympus
  loginShell: /bin/bash
  gecos: The Almighty

groups:
  - users
  - serviceaccounts
  - groups
  - hosts

# needs to be JSON-ish, apparently?
ports: '
[
  {name: ldap, port: 389, protocol: TCP, targetPort: 10389},
  {name: ldaps, port: 636, protocol: TCP, targetPort: 10636}
]
'

meta_storage_mb: 256
data_storage_mb: 2048
...
# vim: set filetype=yaml
