---
# Full reference to a Docker image to use for our chart
image: 'ghcr.io/dreamtrack-net/tinyldap:2024-10-07'

# necessary because the Helm template engine sucks
replicas:
  - openldap-0
  - openldap-1

# TLS certificate details
cert:
  dnsNames:
    - 'ldap.k3s.lab'
  clusterIssuerName: 'k3s-amethyst-issuer'

# LDAP server details
ldap:
  suffix: 'dc=k3s,dc=lab'
  organisation: 'K3S Amethyst'
  description: 'K3S Amethyst'
  rootRdn: 'admin'
  # dev user passwd
  rootPwHash: "{SSHA}gSIuDVYLAQmbamahlILBugabdWE7Q5ld"
  uris: ldap://ldap.k3s.lab/ ldaps://ldap.k3s.lab/
# wedge: topmost "dc" for organisation. How to get this?
  wedge: k3s
# wedge2: users group name
  wedge2: users

# Realm admin user
admin:
  username: zeus
  userPwHash: "{SSHA}JWA/xti9Me/iEt8hKqFBV6JcO6BWTKlV"
  homeDir: /mnt/olympus
  loginShell: /bin/bash
  gecos: The Almighty

# Organisational units
groups:
  - users
  - serviceaccounts
  - groups
  - hosts

# Service ports
# needs to be JSON-ish, apparently?
ports: '
[
  {name: ldap, port: 389, protocol: TCP, targetPort: 10389},
  {name: ldaps, port: 636, protocol: TCP, targetPort: 10636}
]
'

# Pod ports
# needs to be JSON-ish, apparently?
# Required storage/Mb for metadata and data
meta_storage_mb: 256
data_storage_mb: 2048
...
# vim: set filetype=yaml
